# Generated by Django 4.2.9 on 2026-02-14 14:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(help_text="User's question")),
                ("answer", models.TextField(help_text="LLM-generated answer")),
                (
                    "context_used",
                    models.TextField(
                        help_text="Document chunks provided to LLM as context"
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        default=0,
                        help_text="Total tokens (input + output)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        default=0,
                        help_text="Response time in milliseconds",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "was_successful",
                    models.BooleanField(
                        default=True,
                        help_text="Whether an answer was generated (False if no relevant docs)",
                    ),
                ),
                (
                    "num_chunks_retrieved",
                    models.IntegerField(
                        default=0,
                        help_text="Number of chunks retrieved from vector search",
                    ),
                ),
                (
                    "avg_similarity_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Average similarity score of retrieved chunks",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who asked the question",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "queries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("HELPFUL", "Helpful"),
                            ("NOT_HELPFUL", "Not Helpful"),
                            ("HALLUCINATION", "Hallucination Detected"),
                            ("MISSING_INFO", "Missing Information"),
                            ("WRONG_SOURCE", "Wrong Source Used"),
                        ],
                        help_text="Type of feedback",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Rating 1-5 (optional)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Optional comment explaining the feedback"
                    ),
                ),
                (
                    "hallucinated_text",
                    models.TextField(
                        blank=True, help_text="Text that appears to be hallucinated"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_reviewed",
                    models.BooleanField(
                        default=False, help_text="Whether a reviewer has looked at this"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When this was reviewed", null=True
                    ),
                ),
                (
                    "query",
                    models.ForeignKey(
                        help_text="The query being rated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="retrieval.query",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who reviewed this feedback",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User providing feedback",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuerySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(
                        help_text="Similarity score from vector search",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(
                        help_text="Rank in search results (1 = most relevant)"
                    ),
                ),
                (
                    "chunk",
                    models.ForeignKey(
                        help_text="The document chunk used as source",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_in_queries",
                        to="documents.documentchunk",
                    ),
                ),
                (
                    "query",
                    models.ForeignKey(
                        help_text="The query this source was used for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="retrieval.query",
                    ),
                ),
            ],
            options={
                "db_table": "query_sources",
                "ordering": ["query", "rank"],
                "indexes": [
                    models.Index(
                        fields=["query", "rank"], name="query_sourc_query_i_551992_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="query",
            index=models.Index(
                fields=["user", "-created_at"], name="queries_user_id_8abb4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="query",
            index=models.Index(
                fields=["-created_at"], name="queries_created_e3ce76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="query",
            index=models.Index(
                fields=["was_successful"], name="queries_was_suc_41beef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["query"], name="feedback_query_i_5522cb_idx"),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["feedback_type"], name="feedback_feedbac_533c89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["is_reviewed"], name="feedback_is_revi_de239e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["-created_at"], name="feedback_created_d6e06a_idx"
            ),
        ),
    ]
