# Generated by Django 4.2.9 on 2026-02-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, default='0.0.0.0', help_text='IP address of the request', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, default='unknown', help_text='Browser/client user agent', null=True),
        ),
    ]
