# Generated by Django 4.2.9 on 2026-02-14 14:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Document title or name", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the document"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        help_text="Document approval status",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tags for categorization",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Department this document belongs to",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this document was approved",
                        null=True,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who approved this document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who uploaded this document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.IntegerField(
                        help_text="Version number (1, 2, 3...)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded file",
                        upload_to="documents/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "docx", "txt"]
                            )
                        ],
                    ),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "file_type",
                    models.CharField(
                        help_text="File extension (pdf, docx, txt)", max_length=10
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("PROCESSING", "Processing"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                        ],
                        default="UPLOADED",
                        help_text="Current processing status",
                        max_length=20,
                    ),
                ),
                (
                    "total_chunks",
                    models.IntegerField(
                        default=0, help_text="Number of chunks created"
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        blank=True,
                        help_text="Embedding model used (for tracking)",
                        max_length=100,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if processing failed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When processing completed", null=True
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="Parent document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "db_table": "document_versions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chunk_index",
                    models.IntegerField(help_text="Position in document (0-indexed)"),
                ),
                ("text", models.TextField(help_text="Text content of this chunk")),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=768,
                        help_text="Vector embedding for semantic search",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional metadata (page number, section, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "version",
                    models.ForeignKey(
                        help_text="Document version this chunk belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.documentversion",
                    ),
                ),
            ],
            options={
                "db_table": "document_chunks",
            },
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(
                fields=["processing_status"], name="document_ve_process_6332f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(
                fields=["-created_at"], name="document_ve_created_282f2c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentversion",
            unique_together={("document", "version_number")},
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(
                fields=["version", "chunk_index"], name="document_ch_version_545453_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentchunk",
            unique_together={("version", "chunk_index")},
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["status"], name="documents_status_f31a08_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["owner"], name="documents_owner_i_3fe723_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["department"], name="documents_departm_f00baa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["-created_at"], name="documents_created_291bb4_idx"
            ),
        ),
    ]
